### ISSUE TITLE
Client side routing breaks Zebra dataview

### ISSUE THREAD

**Issue by okal** [onaio/hatti#27]
To reproduce

1. Load dataview for a page that doesn't have a map. (This is the context I've seen it in. It could well be the same on forms with geo data.)
2. Click "Summary Charts".
3. Refresh page.

What you'd expect is to see the charts view rendered, but you instead get the table view. Clicking on the "Summary Charts" does not take you to the page, since, as far as secretary is concerned, you're already there i.e. `#/charts`. You have to click on a different tab first, before clicking on the summary charts tab to see it.

**Comment by prabhasp** [comment]
Thanks for the bug report. Marked as high priority, will deal with it as such.
