### ISSUE TITLE
Get tests from Zebra running

### ISSUE THREAD

**Issue by prabhasp** [onaio/hatti#6]

**Comment by prabhasp** [comment]
Started working on the [tests branch](https://github.com/onaio/hatti/tree/tests) but can't get anything working. @royrutto Would appreciate if you could work your amazing magic on getting a simple test or two to work. I can follow up from there. I was getting the same dreaded `No such var: ana/resolve-macro-var` error despite being at 3196.

**Comment by royrutto** [comment]
hey @prabhasp will get to this today.
